# Generated by Django 2.2 on 2019-05-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageView',
            new_name='ViewLog',
        ),
    ]
